import React,{useEffect,useMemo,useState} from 'react';
import {SafeAreaView,View,Text,TextInput,TouchableOpacity,ScrollView,StyleSheet,Alert} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {defaultCategories,paymentMethods,demoExpenses,formatINR,total} from '@daily-expense-tracker/shared';
const today=()=>new Date().toISOString().slice(0,10);
export default function App(){
 const [expenses,setExpenses]=useState([]),[cats,setCats]=useState(defaultCategories),[budget,setBudget]=useState(40000),[tab,setTab]=useState('home'),[amount,setAmount]=useState(''),[desc,setDesc]=useState(''),[category,setCategory]=useState('food'),[method,setMethod]=useState('UPI'),[date,setDate]=useState(today()),[newCat,setNewCat]=useState('');
 useEffect(()=>{(async()=>{let e=JSON.parse(await AsyncStorage.getItem('expenses')||'null')||demoExpenses;let c=JSON.parse(await AsyncStorage.getItem('categories')||'null')||defaultCategories;let b=Number(await AsyncStorage.getItem('budget')||40000);setExpenses(e);setCats(c);setBudget(b)})()},[]);
 useEffect(()=>{if(expenses.length)AsyncStorage.setItem('expenses',JSON.stringify(expenses))},[expenses]);useEffect(()=>{AsyncStorage.setItem('categories',JSON.stringify(cats))},[cats]);useEffect(()=>{AsyncStorage.setItem('budget',String(budget))},[budget]);
 const month=expenses.filter(e=>e.date.startsWith(today().slice(0,7))),spent=total(month),pct=Math.min(100,spent/budget*100);
 const byCat=useMemo(()=>cats.map(c=>({...c,value:total(month.filter(e=>e.category===c.id))})).filter(c=>c.value).sort((a,b)=>b.value-a.value),[month,cats]);
 function add(){if(!Number(amount))return Alert.alert('Enter amount');setExpenses([{id:Date.now().toString(),amount:Number(amount),description:desc||cats.find(c=>c.id===category)?.name,date,category,paymentMethod:method,note:''},...expenses]);setAmount('');setDesc('');setTab('expenses')}
 const Nav=()=> <View style={s.nav}>{[['home','⌂','Home'],['expenses','☷','Expenses'],['add','＋','Add'],['analytics','◔','Analytics'],['budget','◎','Budget']].map(x=><TouchableOpacity onPress={()=>setTab(x[0])} style={s.navItem}><Text style={[s.navIcon,tab===x[0]&&s.navActive]}>{x[1]}</Text><Text style={tab===x[0]?s.navTextActive:s.navText}>{x[2]}</Text></TouchableOpacity>)}</View>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>{tab==='home'&&<><Text style={s.title}>Good morning 👋</Text><Text style={s.muted}>Personal spending dashboard</Text><View style={s.hero}><Text style={s.mutedLight}>This month</Text><Text style={s.total}>{formatINR(spent)}</Text><Text style={s.mutedLight}>{month.length} transactions</Text></View><View style={s.two}><Stat t="Average" v={formatINR(month.length?spent/month.length:0)}/><Stat t="Top category" v={byCat[0]?.name||'—'}/></View><Section title="Recent expenses">{expenses.slice(0,6).map(e=><Row e={e} cats={cats}/>)}</Section></>}
 {tab==='expenses'&&<Section title="Expense history">{expenses.map(e=><Row e={e} cats={cats}/>)}</Section>}
 {tab==='add'&&<Section title="Add expense"><Text style={s.label}>Amount</Text><TextInput style={s.input} keyboardType="numeric" placeholder="₹ 0" value={amount} onChangeText={setAmount}/><Text style={s.label}>Description</Text><TextInput style={s.input} placeholder="What did you spend on?" value={desc} onChangeText={setDesc}/><Text style={s.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{cats.map(c=><TouchableOpacity onPress={()=>setCategory(c.id)} style={[s.chip,category===c.id&&s.selected]}><Text>{c.icon} {c.name}</Text></TouchableOpacity>)}</ScrollView><Text style={s.label}>Payment method</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{paymentMethods.map(x=><TouchableOpacity onPress={()=>setMethod(x)} style={[s.chip,method===x&&s.selected]}><Text>{x}</Text></TouchableOpacity>)}</ScrollView><Text style={s.label}>Date (YYYY-MM-DD)</Text><TextInput style={s.input} value={date} onChangeText={setDate}/><TouchableOpacity style={s.primary} onPress={add}><Text style={s.primaryText}>Add expense</Text></TouchableOpacity></Section>}
 {tab==='analytics'&&<><Section title="Category spending">{byCat.map(c=><View style={s.metric}><View style={s.rowTop}><Text>{c.icon} {c.name}</Text><Text style={s.bold}>{formatINR(c.value)}</Text></View><View style={s.track}><View style={[s.fill,{width:(c.value/spent*100)+'%'}]}/></View></View>)}</Section><Section title="Daily spending">{Object.entries(month.reduce((m,e)=>(m[e.date]=(m[e.date]||0)+e.amount,m),{})).sort().map(([d,v])=><View style={s.rowTop}><Text>{d}</Text><Text style={s.bold}>{formatINR(v)}</Text></View>)}</Section></>}
 {tab==='budget'&&<Section title="Monthly budget"><Text style={s.muted}>Spent</Text><Text style={s.big}>{formatINR(spent)}</Text><Text style={s.muted}>Budget</Text><TextInput style={s.input} keyboardType="numeric" value={String(budget)} onChangeText={x=>setBudget(Number(x)||0)}/><View style={s.track}><View style={[s.fill,{width:pct+'%'}]}/></View><View style={s.rowTop}><Text>{pct.toFixed(0)}% used</Text><Text>{formatINR(Math.max(0,budget-spent))} remaining</Text></View></Section>}
 </ScrollView><Nav/></SafeAreaView>}
const Section=({title,children})=><View style={s.section}><Text style={s.heading}>{title}</Text>{children}</View>;const Stat=({t,v})=><View style={s.stat}><Text style={s.muted}>{t}</Text><Text style={s.statValue}>{v}</Text></View>;const Row=({e,cats})=>{let c=cats.find(c=>c.id===e.category)||cats.at(-1);return <View style={s.row}><Text style={s.emoji}>{c.icon}</Text><View style={{flex:1}}><Text style={s.bold}>{e.description||c.name}</Text><Text style={s.muted}>{c.name} · {e.date}</Text></View><Text style={s.bold}>{formatINR(e.amount)}</Text></View>};
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#f6f7fb'},container:{padding:20,paddingBottom:100},title:{fontSize:30,fontWeight:'800',color:'#172033'},muted:{color:'#6d7788',marginTop:4},mutedLight:{color:'#c5cad3'},hero:{backgroundColor:'#111827',borderRadius:22,padding:22,marginTop:20},total:{fontSize:38,fontWeight:'800',color:'#fff',marginVertical:8},two:{flexDirection:'row',gap:12,marginTop:14},stat:{backgroundColor:'#fff',borderRadius:16,padding:16,flex:1},statValue:{fontSize:18,fontWeight:'800',marginTop:8},section:{backgroundColor:'#fff',borderRadius:18,padding:18,marginTop:16},heading:{fontSize:19,fontWeight:'800',marginBottom:12},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#edf0f4'},rowTop:{flexDirection:'row',justifyContent:'space-between',paddingVertical:8},emoji:{fontSize:24},bold:{fontWeight:'700'},label:{fontWeight:'700',marginTop:12,marginBottom:7},input:{borderWidth:1,borderColor:'#d9dee8',borderRadius:11,padding:13,fontSize:17,backgroundColor:'#fff'},chip:{padding:11,backgroundColor:'#f2f4f8',borderRadius:20,marginRight:8,marginBottom:8},selected:{borderWidth:2,borderColor:'#111827'},primary:{backgroundColor:'#111827',padding:16,borderRadius:12,alignItems:'center',marginTop:18},primaryText:{color:'#fff',fontWeight:'800'},big:{fontSize:36,fontWeight:'800',marginVertical:7},track:{height:12,backgroundColor:'#e7eaf0',borderRadius:20,overflow:'hidden',marginVertical:10},fill:{height:'100%',backgroundColor:'#111827'},metric:{paddingVertical:8},nav:{position:'absolute',bottom:0,left:0,right:0,height:72,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e5e7eb',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},navItem:{alignItems:'center'},navIcon:{fontSize:22,color:'#7b8494'},navText:{fontSize:11,color:'#7b8494'},navActive:{color:'#111827'},navTextActive:{fontSize:11,fontWeight:'800',color:'#111827'}});
