import { StyleSheet } from 'react-native';
const GREEN = '#5FA429',
  GREEN_TINT = '#E8F3D9',
  DARK = '#151717',
  BG = '#F0F2E9',
  BORDER = '#C9D0BC',
  MUTED = '#586154';
const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: BG },
  container: { padding: 20, paddingBottom: 110 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  title: { fontSize: 26, fontWeight: 'bold', color: DARK },
  muted: { color: MUTED, marginTop: 4 },
  mutedLight: { color: '#d7dce6' },
  heroHint: { color: '#e9f5cf', marginTop: 10, fontWeight: 'bold', fontSize: 12 },
  greetRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 6 },
  avatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: GREEN_TINT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmoji: { fontSize: 26 },
  avatarPreviewRow: { alignItems: 'center', marginBottom: 14 },
  avatarCircleLg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: GREEN_TINT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEmojiLg: { fontSize: 44 },
  hero: { backgroundColor: DARK, borderRadius: 22, padding: 22, marginTop: 16 },
  heroRow: { flexDirection: 'row', alignItems: 'center' },
  heroCol: { flex: 1 },
  heroDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.18)',
    marginHorizontal: 16,
  },
  total: { fontSize: 30, fontWeight: 'bold', color: '#fff', marginVertical: 8 },
  totalWarn: { color: '#FFB4AC' },
  two: { flexDirection: 'row', gap: 12, marginTop: 14 },
  stat: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    flex: 1,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  statValue: { fontSize: 18, fontWeight: 'bold', marginTop: 8, color: DARK },
  section: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 18,
    marginTop: 16,
    borderWidth: 1.5,
    borderColor: BORDER,
  },
  heading: { fontSize: 19, fontWeight: 'bold', marginBottom: 12, color: DARK },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  rowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  rowInline: { flexDirection: 'row', gap: 8, alignItems: 'center', marginBottom: 14 },
  emoji: { fontSize: 24 },
  bold: { fontWeight: 'bold', color: DARK },
  danger: { color: '#b23b3b', fontWeight: 'bold' },
  linkBtn: { color: '#2F6FE0', fontWeight: 'bold' },
  label: { fontWeight: 'bold', marginTop: 12, marginBottom: 7, color: DARK, fontSize: 14 },
  smallLabel: { fontSize: 11, fontWeight: 'bold', color: MUTED, marginBottom: 5 },
  hint: { fontSize: 12, color: MUTED, marginTop: 8, lineHeight: 17 },
  dateToggle: { marginTop: 12, marginBottom: 4 },
  input: {
    borderWidth: 1.5,
    borderColor: BORDER,
    borderRadius: 11,
    padding: 13,
    fontSize: 16,
    backgroundColor: '#fff',
    color: DARK,
  },
  multiline: { height: 110, textAlignVertical: 'top', marginTop: 10 },
  catBudgetInput: {
    borderWidth: 1.5,
    borderColor: BORDER,
    borderRadius: 9,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    backgroundColor: '#fff',
    color: DARK,
    minWidth: 100,
    textAlign: 'right',
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: BG,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: BORDER,
  },
  chipText: { color: DARK, fontSize: 14 },
  selected: { borderWidth: 2, borderColor: DARK, backgroundColor: GREEN_TINT },
  primary: {
    backgroundColor: DARK,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 18,
  },
  btnRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  primaryText: { color: '#fff', fontWeight: 'bold', fontSize: 15 },
  secondary: {
    backgroundColor: GREEN_TINT,
    padding: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#cfe3b3',
  },
  secondaryText: { color: '#33500f', fontWeight: 'bold' },
  cancel: { padding: 14, alignItems: 'center', marginTop: 8 },
  cancelText: { color: MUTED, fontWeight: 'bold' },
  addCatBtn: {
    backgroundColor: DARK,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 11,
  },
  catGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  catChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: BG,
    borderRadius: 20,
    paddingVertical: 9,
    paddingHorizontal: 13,
    borderWidth: 1,
    borderColor: BORDER,
  },
  big: { fontSize: 36, fontWeight: 'bold', marginVertical: 7, color: DARK },
  alert: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#FBE4C0',
    color: '#5c3a06',
    fontWeight: 'bold',
  },
  track: {
    height: 12,
    backgroundColor: BG,
    borderRadius: 20,
    overflow: 'hidden',
    marginVertical: 10,
    borderWidth: 1,
    borderColor: BORDER,
  },
  fill: { height: '100%', backgroundColor: GREEN },
  fillWarn: { backgroundColor: '#D98416' },
  metric: { paddingVertical: 8 },
  empty: { alignItems: 'center', paddingVertical: 26, gap: 8 },
  emptyIcon: { fontSize: 30 },
  emptyText: { color: MUTED, textAlign: 'center', paddingHorizontal: 12 },
  calRow: { flexDirection: 'row', marginTop: 10 },
  calDow: { flex: 1, textAlign: 'center', fontSize: 11, fontWeight: 'bold', color: MUTED },
  calGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  calCell: {
    width: '14.28%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 2,
  },
  calOut: { opacity: 0.35 },
  calToday: { borderWidth: 1.5, borderColor: DARK, borderRadius: 10 },
  calSpend: { backgroundColor: GREEN_TINT, borderRadius: 10 },
  calSelectedCell: { backgroundColor: DARK, borderRadius: 10 },
  calDay: { fontSize: 12, fontWeight: 'bold', color: DARK },
  calDaySelected: { color: '#fff' },
  calAmt: { fontSize: 8, fontWeight: 'bold', color: '#3d6b12' },
  calSelected: { borderTopWidth: 1, borderTopColor: BORDER, paddingTop: 10, marginTop: 6 },
  nav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    minHeight: 74,
    backgroundColor: '#fff',
    borderTopWidth: 1.5,
    borderTopColor: BORDER,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    paddingVertical: 2,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 6,
    paddingBottom: 6,
    gap: 3,
  },
  navText: {
    fontSize: 9,
    color: '#5b645b',
    fontWeight: '600',
    textAlign: 'center',
    includeFontPadding: false,
  },
  navTextActive: {
    fontSize: 9,
    fontWeight: 'bold',
    color: DARK,
    textAlign: 'center',
    includeFontPadding: false,
  },
  calNavBtn: { padding: 4 },
  lockWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, gap: 6 },
  pinInput: {
    width: 160,
    textAlign: 'center',
    fontSize: 22,
    letterSpacing: 8,
    marginTop: 20,
    marginBottom: 6,
  },
  snackbar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 88,
    backgroundColor: DARK,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  snackbarText: { color: '#fff', fontSize: 14, flex: 1, marginRight: 12 },
  snackbarAction: { color: GREEN, fontWeight: 'bold', fontSize: 14 },
  positive: { color: '#3d6b12' },
  streakBadge: {
    backgroundColor: '#FBE4C0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 14,
  },
  streakText: { color: '#7a4d0a', fontWeight: 'bold', fontSize: 13 },
  quickChip: {
    backgroundColor: GREEN_TINT,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 10,
    minWidth: 110,
    borderWidth: 1,
    borderColor: '#cfe3b3',
  },
  quickChipName: { color: DARK, fontWeight: 'bold', fontSize: 13 },
  quickChipAmount: { color: '#33500f', fontSize: 13, marginTop: 4 },
  swipeEdit: {
    backgroundColor: '#2F6FE0',
    justifyContent: 'center',
    alignItems: 'center',
    width: 64,
  },
  swipeDelete: {
    backgroundColor: '#b23b3b',
    justifyContent: 'center',
    alignItems: 'center',
    width: 64,
  },
  onboardEmoji: { fontSize: 52, textAlign: 'center', marginBottom: 8 },
  onboardRow: { flexDirection: 'row', gap: 14, alignItems: 'flex-start', marginBottom: 22 },
  onboardIcon: { fontSize: 26 },
  incomeRow: { borderLeftWidth: 3, borderLeftColor: '#3d6b12', paddingLeft: 6 },
  pill: {
    paddingVertical: 7,
    paddingHorizontal: 13,
    borderRadius: 18,
    backgroundColor: BG,
    borderWidth: 1,
    borderColor: BORDER,
    marginRight: 6,
  },
  pillActive: {
    backgroundColor: DARK,
    borderColor: DARK,
  },
  pillText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: MUTED,
  },
  pillTextActive: {
    color: '#fff',
  },
});

export { DARK, GREEN, GREEN_TINT, BG, BORDER, MUTED };
export default s;
