import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {PieChart,Pie,Cell,Tooltip,ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,BarChart,Bar} from 'recharts';
import {defaultCategories,paymentMethods,demoExpenses,formatINR,total} from '@daily-expense-tracker/shared';
import './style.css';

const today=()=>new Date().toISOString().slice(0,10);
function App(){
 const [expenses,setExpenses]=useState(()=>JSON.parse(localStorage.getItem('det-expenses')||'null')||demoExpenses);
 const [categories,setCategories]=useState(()=>JSON.parse(localStorage.getItem('det-categories')||'null')||defaultCategories);
 const [budget,setBudget]=useState(()=>Number(localStorage.getItem('det-budget')||40000));
 const [tab,setTab]=useState('dashboard'),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('all');
 useEffect(()=>localStorage.setItem('det-expenses',JSON.stringify(expenses)),[expenses]);useEffect(()=>localStorage.setItem('det-categories',JSON.stringify(categories)),[categories]);useEffect(()=>localStorage.setItem('det-budget',budget),[budget]);
 const month=expenses.filter(e=>e.date.startsWith(today().slice(0,7))); const monthTotal=total(month);
 const byCat=useMemo(()=>categories.map(c=>({name:c.name,value:total(month.filter(e=>e.category===c.id))})).filter(x=>x.value),[month,categories]);
 const daily=useMemo(()=>{let m={};month.forEach(e=>m[e.date]=(m[e.date]||0)+Number(e.amount));return Object.entries(m).sort().map(([date,amount])=>({date:date.slice(5),amount}))},[month]);
 const top=byCat.slice().sort((a,b)=>b.value-a.value)[0];
 const visible=expenses.filter(e=>(e.description+' '+e.note).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||e.category===filter)).sort((a,b)=>b.date.localeCompare(a.date));
 function saveExpense(x){setExpenses(p=>editing?p.map(e=>e.id===x.id?x:e):[x,...p]);setEditing(null);setTab('expenses')}
 function remove(id){if(confirm('Delete this expense?'))setExpenses(p=>p.filter(e=>e.id!==id))}
 function exportCSV(){const rows=[['Date','Amount','Category','Description','Payment Method','Note'],...expenses.map(e=>[e.date,e.amount,categories.find(c=>c.id===e.category)?.name||'',e.description,e.paymentMethod,e.note||''])];const blob=new Blob([rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='daily-expenses.csv';a.click()}
 return <div className="app"><aside><div className="brand">💰 <span>DailyExpense</span></div><div className="nav">{[['dashboard','⌂','Dashboard'],['expenses','☷','Expenses'],['analytics','◔','Analytics'],['budget','◎','Budget'],['categories','◇','Categories']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])}><b>{x[1]}</b>{x[2]}</button>)}</div><div className="sideNote">Phase 1–5<br/><small>Web + Mobile</small></div></aside>
 <main><header><div><div className="eyebrow">PERSONAL FINANCE</div><h1>{tab==='dashboard'?'Good morning 👋':tab[0].toUpperCase()+tab.slice(1)}</h1><p>Track everyday spending without the clutter.</p></div><button className="primary" onClick={()=>{setEditing(null);setTab('add')}}>＋ Add expense</button></header>
 {tab==='dashboard'&&<><section className="cards"><Metric title="This month" value={formatINR(monthTotal)}/><Metric title="Transactions" value={month.length}/><Metric title="Avg. transaction" value={formatINR(month.length?monthTotal/month.length:0)}/><Metric title="Top category" value={top?.name||'—'}/></section><div className="grid"><Panel title="Spending trend"><Trend data={daily}/></Panel><Panel title="Category breakdown"><Donut data={byCat}/></Panel></div><Panel title="Recent expenses"><ExpenseList items={expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6)} cats={categories} onEdit={x=>{setEditing(x);setTab('add')}} onDelete={remove}/></Panel></>}
 {tab==='expenses'&&<Panel title="Expense history"><div className="toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search description or note"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option value={c.id}>{c.icon} {c.name}</option>)}</select><button onClick={exportCSV}>Export CSV</button></div><ExpenseList items={visible} cats={categories} onEdit={x=>{setEditing(x);setTab('add')}} onDelete={remove}/></Panel>}
 {tab==='add'&&<ExpenseForm initial={editing} cats={categories} onCancel={()=>setTab('expenses')} onSave={saveExpense}/>} 
 {tab==='analytics'&&<><div className="grid"><Panel title="Category spending"><Donut data={byCat}/></Panel><Panel title="Daily spending"><Trend data={daily}/></Panel></div><Panel title="Monthly overview"><MonthlyBars expenses={expenses}/></Panel></>}
 {tab==='budget'&&<Budget budget={budget} setBudget={setBudget} spent={monthTotal}/>} 
 {tab==='categories'&&<CategoryManager cats={categories} setCats={setCategories}/>} 
 </main></div>
}
const Metric=({title,value})=><div className="card"><span>{title}</span><strong>{value}</strong></div>;
const Panel=({title,children})=><section className="panel"><div className="panelHead"><h2>{title}</h2></div>{children}</section>;
function ExpenseList({items,cats,onEdit,onDelete}){return <div>{items.map(e=>{let c=cats.find(c=>c.id===e.category)||cats.at(-1);return <div className="expense"><span className="icon">{c.icon}</span><div className="grow"><b>{e.description||c.name}</b><small>{c.name} · {e.date} · {e.paymentMethod}</small></div><strong>{formatINR(e.amount)}</strong><button className="mini" onClick={()=>onEdit(e)}>Edit</button><button className="mini danger" onClick={()=>onDelete(e.id)}>Delete</button></div>})}{!items.length&&<div className="empty">No expenses found.</div>}</div>}
function ExpenseForm({initial,cats,onCancel,onSave}){const [f,setF]=useState(initial||{id:null,date:today(),amount:'',category:cats[0]?.id,description:'',paymentMethod:'UPI',note:''});const set=(k,v)=>setF({...f,[k]:v});return <Panel title={initial?'Edit expense':'Add expense'}><form className="form" onSubmit={e=>{e.preventDefault();if(Number(f.amount)>0)onSave({...f,amount:Number(f.amount),id:f.id||Date.now().toString()})}}><label>Amount (₹)<input autoFocus type="number" min="1" value={f.amount} onChange={e=>set('amount',e.target.value)} required/></label><label>Date<input type="date" value={f.date} onChange={e=>set('date',e.target.value)} required/></label><label>Category<select value={f.category} onChange={e=>set('category',e.target.value)}>{cats.map(c=><option value={c.id}>{c.icon} {c.name}</option>)}</select></label><label>Payment method<select value={f.paymentMethod} onChange={e=>set('paymentMethod',e.target.value)}>{paymentMethods.map(x=><option>{x}</option>)}</select></label><label className="wide">Description<input value={f.description} onChange={e=>set('description',e.target.value)} placeholder="e.g. Lunch with family"/></label><label className="wide">Notes<textarea value={f.note} onChange={e=>set('note',e.target.value)} placeholder="Optional note"/></label><div className="actions"><button type="button" onClick={onCancel}>Cancel</button><button className="primary">{initial?'Save changes':'Add expense'}</button></div></form></Panel>}
function CategoryManager({cats,setCats}){const [name,setName]=useState('');function add(){if(!name.trim())return;setCats([...cats,{id:'custom-'+Date.now(),name:name.trim(),icon:'🏷️'}]);setName('')}return <Panel title="Categories"><div className="toolbar"><input value={name} onChange={e=>setName(e.target.value)} placeholder="New category name"/><button className="primary" onClick={add}>＋ Add category</button></div><div className="catGrid">{cats.map(c=><div className="cat"><span>{c.icon}</span><b>{c.name}</b></div>)}</div></Panel>}
function Budget({budget,setBudget,spent}){const pct=Math.min(100,budget?spent/budget*100:0);return <Panel title="Monthly budget"><div className="budgetTop"><div><span>Spent</span><h2>{formatINR(spent)}</h2></div><div><span>Budget</span><input className="budgetInput" type="number" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></div></div><div className="progress"><i style={{width:pct+'%'}}/></div><div className="budgetMeta"><b>{pct.toFixed(0)}% used</b><span>{formatINR(Math.max(0,budget-spent))} remaining</span></div>{pct>=80&&<div className="alert">⚠️ You are approaching your monthly budget.</div>}</Panel>}
const Donut=({data})=><div className="chart"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={60} outerRadius={95}>{data.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={v=>formatINR(v)}/></PieChart></ResponsiveContainer></div>;
const Trend=({data})=><div className="chart"><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip formatter={v=>formatINR(v)}/><Line type="monotone" dataKey="amount" strokeWidth={3}/></LineChart></ResponsiveContainer></div>;
function MonthlyBars({expenses}){let m={};expenses.forEach(e=>{let k=e.date.slice(0,7);m[k]=(m[k]||0)+Number(e.amount)});let d=Object.entries(m).sort().slice(-6).map(([month,amount])=>({month,amount}));return <div className="chart"><ResponsiveContainer><BarChart data={d}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={v=>formatINR(v)}/><Bar dataKey="amount"/></BarChart></ResponsiveContainer></div>}
createRoot(document.getElementById('root')).render(<App/>);
